@URL=http://localhost:3000/users

### CRIAR USUARIO
POST {{URL}}
Content-Type: application/json

{
    "name": "Juca",
    "email": "juca@gmail.com",
    "password": "1234"
}


### Obter todos os usuários
GET {{URL}}?name
Authorization: 1234



### Obter um por Id
GET {{URL}}/63372f8ad58b92203f526def
Authorization: 1234